import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from "@/fsd-app";
import { Toaster } from "@/shared/ui/ui/sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Toaster />
        <div className="fixed top-0 left-0 right-0 bottom-0 flex max-md:flex-col-reverse">
          <RootProvider>{children}</RootProvider>
        </div>
      </body>
    </html>
  );
}
