import { z } from 'zod';

export const envSchema = z.object({
  NODE_ENV: z.enum(['development', 'production']),
  JWT_SECRET: z.string(),
  JWT_ACCESS_TOKEN_TTL: z.string(),
  JWT_REFRESH_TOKEN_TTL: z.string(),
  POSTGRES_USER: z.string(),
  POSTGRES_PASSWORD: z.string(),
  POSTGRES_DATABASE: z.string(),
  POSTGRES_PORT: z.string(),
  POSTGRES_HOST: z.string(),
  DATABASE_URI: z.string(),
  FRONTEND_URL: z.string(),
  BACKEND_URL: z.string(),
  GOOGLE_CLIENT_ID: z.string(),
  GOOGLE_CALLBACK_URL: z.string(),
  GOOGLE_CLIENT_SECRET: z.string(),
  YANDEX_CLIENT_ID: z.string().optional(),
  YANDEX_CLIENT_SECRET: z.string().optional(),
  YANDEX_CALLBACK_URL: z.string().optional(),
  S3_ACCESS_KEY_ID: z.string(),
  S3_SECRET_ACCESS_KEY_ID: z.string(),
  COOKIE_SECRET: z.string(),
  OPENROUTER_API_KEY: z.string().optional(),
  OPENROUTER_CHAT_MODEL: z.string().optional(),
  OPENROUTER_VISION_MODEL: z.string().optional(),
  OPENROUTER_IMAGE_MODEL: z.string().optional(),
  OPENROUTER_EMBEDDING_MODEL: z.string().optional(),
  EMBEDDING_DIMENSIONS: z.string().optional(),
});
